// Client brand data
export const clients = [
  { active: true, id: "cocoricocafe", name: "Cocorico", nameKo: "코코리코", category: "Restaurant & Bar", emoji: "☕", colors: ["#95d8e3", "#dedfb8", "#000000", "#F5F0E8"], colorNames: ["Sky Blue", "Sage Cream", "Black", "Warm White"], tone: ["Casual", "Trendy", "Social", "Cozy", "Late-night vibe"], instagram: "@cocoricocafe", website: "https://cocoricocafe.ca/", phone: "(604) 687-0424", address: "1290 Robson St, Vancouver, BC V6E 1C1", highlights: ["Brunch & cafe menu", "Late-night dining", "Cocktails", "Robson Street location", "Shareable food presentation"], schedule: "Weekly", driveFolderId: "1odvvWOvaMoS7DcEC_sS9ta9EPFUqDrws", logoFolderId: "1TtdhxicGhYG7jOT7rHK-USVgmJtJozmc" },
  { active: true, id: "onggi", name: "Onggi Korean Cuisine", nameKo: "옹기", category: "Korean Restaurant", emoji: "🍲", colors: ["#9d1e20", "#e9993b", "#153544", "#000000", "#F5EFE0"], colorNames: ["Deep Red", "Amber", "Navy", "Black", "Warm Beige"], tone: ["Traditional", "Authentic", "Warm", "Comforting"], instagram: "@onggi_korean_cuisine", website: "https://theonggi.ca/", phone: "(604) 420-0277", address: "#103 – 4501 North Rd, Burnaby, BC V3N 4R7", highlights: ["비빔밥", "삼겹살·김치찜", "감자탕", "불고기", "냉면", "해물파전", "떡볶이+핫도그", "만두", "Kalguksu"], schedule: "Weekly", driveFolderId: "1pWBZAoYf9HZJpoIwLirxWhCfebKlak6z", logoFolderId: "1QGnuDFMvfDprIOG_4cLiGOswq-Do1g7o" },
  { active: true, id: "twohorns", name: "Two Horns BBQ", nameKo: "투혼 BBQ", category: "Korean & Japanese BBQ", emoji: "🥩", colors: ["#1a1a1a", "#C0272D", "#D4AF37", "#2a2a2a"], colorNames: ["Charcoal", "Bold Red", "Gold", "Dark Grey"], tone: ["Luxury", "Premium", "Authentic", "Social"], instagram: "@twohornsbbq", website: "https://www.twohorns.ca/", phone: "(604) 214-1488", address: "120-4231 Hazelbridge Way, Richmond, BC V6X 3L7", highlights: ["Korean BBQ", "Japanese BBQ", "Group dining", "Premium meat cuts", "Drinking atmosphere"], schedule: "Weekly", driveFolderId: "1YqvoYDm1m7b98ejnjntOJDNPje81joar", logoFolderId: "1H_hinmoRxvIg4A6a2aZStXeD5lPVbbcx" },
  { active: true, id: "gamisushi", name: "Gami Sushi", nameKo: "가미 Sushi", category: "Sushi Restaurant", emoji: "🍣", colors: ["#0D0D0D", "#C9A84C", "#F5F0E8", "#8B1A1A", "#2A2A2A"], colorNames: ["Deep Black", "Gold", "Ivory", "Dark Red", "Charcoal"], tone: ["Upscale", "Premium", "Japanese fine dining", "Dark & Gold"], instagram: "@gamisushi_ca", website: "https://gamisushi.ca/", phone: "(604) 272-1653", address: "#126 – 10111 No. 3 Rd, Richmond, BC V7A 1W6", highlights: ["Sushi rolls", "Fresh fish", "Japanese dining experience"], schedule: "Weekly", driveFolderId: "1Hlnns8z56_C3LYi79aFNo6NgvJ2bDk3I", logoFolderId: "1c15GHnmiiMyLeu334-MHnDe3_y-TaBbA" },
  { active: true, id: "gakesushi", name: "Gake Sushi & Lounge", nameKo: "가케 Sushi", category: "Sushi Restaurant & Lounge", emoji: "🍱", colors: ["#F2EBE0", "#8B1A1A", "#2C2C2C", "#D4B896"], colorNames: ["Warm Beige", "Deep Red", "Dark Grey", "Sand"], tone: ["Modern Japanese", "Clean", "Premium casual"], instagram: "@gakesushi", website: "https://gake.ca/", phone: "(604) 559-4899", address: "3605 W 4th Ave, Vancouver, BC V6R 1P2", highlights: ["Sushi rolls", "Premium sashimi", "Premium sake", "Premium bento", "Course menu for holidays", "Kitsilano location"], schedule: "Weekly + Holiday", driveFolderId: "1kBiQwU0g5y1ApsdXxHc5MPjBvUtEguAL", logoFolderId: "1ekHiYUdFsm4LVH380xHBQU6KRurK-kGh" },
  { active: true, id: "commeliving", name: "Comme Living", nameKo: "꼼므 리빙", category: "Furniture / Home & Living", emoji: "🛋️", colors: ["#F0EDE8", "#D4C9BC", "#2C2C2C", "#A89880"], colorNames: ["Cream", "Warm Taupe", "Charcoal", "Mocha"], tone: ["Minimal", "Trendy", "Modern lifestyle", "Editorial"], instagram: "@commeliving", website: "https://commeliving.com", phone: "+1 (604) 356-5430", address: "7360 River Road #100, Richmond, BC V6X 1X6", highlights: ["공동구매 프로모션", "Directly imported from Hyundai Livart Korea", "Living/interior styling", "Lifestyle branding"], schedule: "Weekly + Promotions", driveFolderId: "19no0wCFvVQPDBKUhr3yZN-EeW3KB3i0L", logoFolderId: "13aszmDNCK_xkoy8UVBxxHcgj_X0uBfgP" },
  { active: true, id: "acuplus", name: "AcuPlus Clinic", nameKo: "ACU Plus", category: "Acupuncture & Facial Aesthetics", emoji: "🌿", colors: ["#FAFAF8", "#2D4A3E", "#E8E0D0", "#8BA888"], colorNames: ["Off White", "Dark Green", "Cream", "Sage"], tone: ["Professional", "Calming", "Premium wellness"], instagram: "@acuplus_ca", website: "https://acuplusclinic.com", phone: "236-979-6464", address: "9600 Cameron St #303A, Burnaby, BC V3J 7N3", highlights: ["Acupuncture", "Facial rejuvenation", "Osteopathy", "ICBC treatments", "Pain management", "Micro needling"], schedule: "Weekly", driveFolderId: "1fNl_tV037w7QVgMWR_pb7V24bguImGhB", logoFolderId: "16LBwbhwShGyRNTUrFRYi3H55ByflNtuC" },
  { active: true, id: "truetherapy", name: "True Therapy Clinic", nameKo: "True Therapy", category: "RMT Clinic", emoji: "💆", colors: ["#FAFAF8", "#2D4A3E", "#E8E0D0", "#8BA888"], colorNames: ["Off White", "Dark Green", "Cream", "Sage"], tone: ["Professional", "Trustworthy", "Recovery-focused"], instagram: "@truetherapyclinic.ca", website: "https://truetherapyclinic.ca", phone: "604-299-9292", address: "9600 Cameron St #303A, Burnaby, BC V3J 7N3", highlights: ["Registered Massage Therapy", "ICBC direct billing", "Pain relief", "Recovery & rehabilitation", "Personalized treatments"], schedule: "Weekly", driveFolderId: "1Yv18zKi4Tf3z3Z0T4y2MxbU6djAPyRUv", logoFolderId: "16LBwbhwShGyRNTUrFRYi3H55ByflNtuC" },
  { active: true, id: "mistyblue", name: "Misty Blue Flowers", nameKo: "Misty Blue", category: "Florist / E-commerce", emoji: "💐", colors: ["#7559C0", "#3768AB", "#95A7BC", "#2C2C2C"], colorNames: ["Violet", "Blue", "Steel Blue", "Charcoal"], tone: ["Editorial", "Elegant", "Modern", "Expressive"], instagram: "@mistyblue.ca", website: "https://mistyblueflowers.ca", phone: "+1 778-788-0505", address: "#404-1688 152 St, South Surrey, BC", highlights: ["Flower arrangements", "Same-day delivery", "Seasonal collections", "Mother's Day / Graduation campaigns", "South Surrey & Vancouver", "Wedding florals", "Floral Academy"], schedule: "Weekly + Holiday", driveFolderId: "1ncdb0-rlxgOIu7gn-5i4I2zkjO_7kK3v", logoFolderId: "1IILYa0cNwOPs0hkW5G8IzAMlRXQsVUFr" },
  { active: true, id: "joayotherapy", name: "Joayo Therapy", nameKo: "Joayo Therapy", category: "Wellness Clinic", emoji: "🧘", colors: ["#FFFFFF", "#1a1a1a", "#C4A0A0", "#A87878", "#F5EFEF"], colorNames: ["White", "Black", "Muted Rose", "Dusty Mauve", "Blush White"], tone: ["Holistic", "Modern wellness", "Approachable", "Clean"], instagram: "@joayotherapy", website: "https://www.joayotherapy.ca/", phone: "(604) 558-1347", address: "100C-4664 Lougheed Hwy, Burnaby, BC V5C 5T5", highlights: ["Chiropractic", "Physiotherapy", "RMT", "Pilates", "Acupuncture", "Kinesiology", "Naturopathic Medicine"], schedule: "Weekly", driveFolderId: "1ktufJtDVYQwPPIKvMoDNEd1apjG9pXuY", logoFolderId: "1Y4idsJ9YHv7107MNZ17RRbW4g19VnqI3", canvaProjectUrl: "https://www.canva.com/design/DAHNb-Y6rrg/G_SUNFTmtpPxdp3IRlxLLg/edit" },
  { active: true, id: "joayopilates", name: "Joayo Pilates", nameKo: "Joayo Pilates", category: "Fitness / Pilates Studio", emoji: "🤸", colors: ["#FFFFFF", "#1a1a1a", "#D4B896", "#C8A882", "#F5F0EA"], colorNames: ["White", "Black", "Warm Tan", "Gold Beige", "Off White"], tone: ["Modern", "Approachable", "Motivating", "Welcoming"], instagram: "@joayopilates", website: "TBD", phone: "(604) 558-1347", address: "100C-4664 Lougheed Hwy, Burnaby, BC V5C 5T5", highlights: ["Reformer Pilates", "Private Sessions", "Group Classes", "Core Strength", "Posture Improvement", "Beginner-Friendly"], schedule: "Weekly", driveFolderId: "1ktufJtDVYQwPPIKvMoDNEd1apjG9pXuY", logoFolderId: "1Y4idsJ9YHv7107MNZ17RRbW4g19VnqI3", canvaProjectUrl: "https://www.canva.com/design/DAHNgHv-UM4/4dYLABVafebf8d1pkdF8Qg/edit" },
  { active: true, id: "changstaekwondo", name: "Chang's Taekwondo", nameKo: "태권도창스", category: "Martial Arts / Education", emoji: "🥋", colors: ["#1A2B6B", "#C0272D", "#1a1a1a", "#FFFFFF"], colorNames: ["Deep Blue", "Deep Red", "Black", "White"], tone: ["Motivational", "Disciplined", "Family-friendly", "Energetic"], instagram: "@changstaekwondo", website: "https://www.changstaekwondo.ca/", highlights: ["Taekwondo training", "Kids classes", "Cute illustrations for kids", "Discipline & confidence building"], schedule: "Weekly", driveFolderId: "1f_JyaB1U-IoU5zR-oeKrpTtcfH43Fn3g", logoFolderId: "1NDG_uIglbjDWXKnB_HH8ChHQjXdUNb5h" },
  { active: true, id: "queenstherapy", name: "Queen's Therapy", nameKo: "Queen's Therapy", category: "Acupuncture & RMT Clinic", emoji: "👑", colors: ["#FAF6F2", "#E8A598", "#D4756A", "#6B4C3B", "#3A2E2A"], colorNames: ["Ivory", "Soft Coral", "Dusty Rose", "Mocha Brown", "Dark Brown"], tone: ["Warm", "Calming", "Professional", "Premium wellness"], instagram: "@queenstherapycoquitlam", website: "https://queenstherapy.janeapp.com", phone: "(604) 939-5052", address: "1140 Austin Ave #150, Coquitlam, BC V3K 3P5", highlights: ["Acupuncture", "Glass/Fire Cupping", "RMT", "Facial Rejuvenation", "HIFU Ultrasound", "ICBC treatments", "Body Slim Therapy"], schedule: "Weekly", driveFolderId: "1PjmjBgyI0g1lx5EZYebR015eRS6W-uy4", logoFolderId: null, canvaProjectUrl: "https://www.canva.com/design/DAHNhRKu3bQ/1f7wV3p6s_HcBDJQatIFGg/edit" },
  { active: true, id: "wolha", name: "WOLHA", nameKo: "월하", category: "Premium Korean Rice Wine", emoji: "🌕", colors: ["#17244A", "#C6A27B", "#F3EEE5", "#8B6B53", "#1D1A1A"], colorNames: ["Midnight Navy", "Warm Gold", "Ivory", "Clay Brown", "Charcoal Black"], tone: ["Calm", "Artisan", "Minimal", "Sophisticated", "Quiet Luxury"], instagram: "@wolha_ricewine", website: "https://wolha.ca", phone: "778-319-4113", address: "#409-1485 Coast Meridian Rd, Port Coquitlam, BC (픽업 전 사전 예약 필수)", highlights: ["Premium Korean Rice Wine", "Small batch fermentation", "Vancouver Exclusive", "Natural fermentation", "Alive with probiotics", "Handcrafted", "Modern Korean craft"], schedule: "Weekly", driveFolderId: "1DJ79pEQpeIl-spEaZzqeCbF1c9mDta4t", logoFolderId: "1WiTpf2pRoeZXnnu0egj-wKY20IXW1S3H" },
];

export const categories = ["All", "Restaurant", "Sushi", "Wellness", "Fitness", "Retail", "Florist", "Martial Arts", "Beverage"];

export const categoryMap = {
  Restaurant: ["cocoricocafe", "onggi", "twohorns"],
  Sushi: ["gamisushi", "gakesushi"],
  Wellness: ["acuplus", "truetherapy", "joayotherapy", "queenstherapy"],
  Fitness: ["joayopilates", "changstaekwondo"],
  Retail: ["commeliving"],
  Florist: ["mistyblue"],
  "Martial Arts": ["changstaekwondo"],
  Beverage: ["wolha"],
};
