// Client brand data
export const clients = [
  { active: true,  "Coco Rico Cafe", nameKo: "코코리코", category: "Cafe & Restaurant", emoji: "☕", colors: ["#95d8e3", "#dedfb8", "#000000", "#F5F0E8"], colorNames: ["Sky Blue", "Sage Cream", "Black", "Warm White"], tone: ["Casual", "Trendy", "Social", "Cozy", "Late-night vibe"], instagram: "@cocoricocafe", website: "https://cocoricocafe.ca/", highlights: ["Brunch & cafe menu", "Late-night dining", "Cocktails", "Robson Street location", "Shareable food presentation"], schedule: "Weekly", driveFolderId: "1odvvWOvaMoS7DcEC_sS9ta9EPFUqDrws", logoFolderId: "1TtdhxicGhYG7jOT7rHK-USVgmJtJozmc", chatgptPrompt: `You are a social media content creator for Coco Rico Cafe, a trendy late-night cafe on Robson Street, Vancouver. Brand colors: sky blue (#95d8e3), sage cream (#dedfb8), black, warm white. Tone: casual, trendy, social, cozy. Focus on: brunch, late-night dining, cocktails, shareable food. Always write in a fun, social-media-friendly voice targeting young adults in Vancouver.` },
  { active: true,  "Onggi Korean Cuisine", nameKo: "옹기", category: "Korean Restaurant", emoji: "🍲", colors: ["#9d1e20", "#e9993b", "#153544", "#000000", "#F5EFE0"], colorNames: ["Deep Red", "Amber", "Navy", "Black", "Warm Beige"], tone: ["Traditional", "Authentic", "Warm", "Comforting"], instagram: "@onggi_korean_cuisine", website: "https://theonggi.ca/", highlights: ["비빔밥", "삼겹살·김치찜", "감자탕", "불고기", "냉면", "해물파전", "떡볶이+핫도그", "만두", "Kalguksu"], schedule: "Weekly", driveFolderId: "1pWBZAoYf9HZJpoIwLirxWhCfebKlak6z", logoFolderId: "1QGnuDFMvfDprIOG_4cLiGOswq-Do1g7o", chatgptPrompt: `You are a social media content creator for Onggi Korean Cuisine, an authentic Korean restaurant in Vancouver. Brand colors: deep red (#9d1e20), amber (#e9993b), navy (#153544). Tone: traditional Korean, authentic, warm, comforting. Focus on: Korean comfort food, family-style dining, traditional dishes like bibimbap, samgyeopsal, gamjatang, bulgogi. Write with warmth and authenticity.` },
  { active: true,  "Two Horns BBQ", nameKo: "투혼 BBQ", category: "Korean & Japanese BBQ", emoji: "🥩", colors: ["#1a1a1a", "#C0272D", "#D4AF37", "#2a2a2a"], colorNames: ["Charcoal", "Bold Red", "Gold", "Dark Grey"], tone: ["Luxury", "Premium", "Authentic", "Social"], instagram: "@twohornsbbq", website: "https://www.twohorns.ca/", highlights: ["Korean BBQ", "Japanese BBQ", "Group dining", "Premium meat cuts", "Drinking atmosphere"], schedule: "Weekly", driveFolderId: "1YqvoYDm1m7b98ejnjntOJDNPje81joar", logoFolderId: "1H_hinmoRxvIg4A6a2aZStXeD5lPVbbcx", chatgptPrompt: `You are a social media content creator for Two Horns Korean & Japanese BBQ, a premium BBQ restaurant in Vancouver. Brand colors: charcoal black, bold red (#C0272D), gold (#D4AF37). Tone: luxury, premium, authentic BBQ experience. Focus on: premium meat quality, group dining experience, Korean and Japanese BBQ culture. Write with sophistication and excitement.` },
  { active: true,  "Gami Sushi", nameKo: "가미 Sushi", category: "Sushi Restaurant", emoji: "🍣", colors: ["#FFFFFF", "#1a1a1a", "#E8E0D5", "#B5A99A"], colorNames: ["White", "Black", "Sand", "Warm Grey"], tone: ["Clean", "Minimal", "Japanese aesthetic", "Fresh"], instagram: "@gamisushi_ca", website: "https://gamisushi.ca/", highlights: ["Sushi rolls", "Fresh fish", "Japanese dining experience"], schedule: "Weekly", driveFolderId: "1Hlnns8z56_C3LYi79aFNo6NgvJ2bDk3I", logoFolderId: "1c15GHnmiiMyLeu334-MHnDe3_y-TaBbA", chatgptPrompt: `You are a social media content creator for Gami Sushi, a clean and minimal Japanese sushi restaurant in Vancouver. Brand colors: white, black, sand, warm grey. Tone: clean, minimal, Japanese dining aesthetic. Focus on: fresh fish quality, sushi craftsmanship, Japanese dining experience. Write with elegance and simplicity.` },
  { active: true,  "Gake Sushi", nameKo: "가케 Sushi", category: "Sushi Restaurant", emoji: "🍱", colors: ["#F2EBE0", "#8B1A1A", "#2C2C2C", "#D4B896"], colorNames: ["Warm Beige", "Deep Red", "Dark Grey", "Sand"], tone: ["Modern Japanese", "Clean", "Premium casual"], instagram: "@gakesushi", website: "https://gake.ca/", highlights: ["Sushi rolls", "Premium sashimi", "Premium sake", "Premium bento", "Course menu for holidays"], schedule: "Weekly + Holiday", driveFolderId: "1kBiQwU0g5y1ApsdXxHc5MPjBvUtEguAL", logoFolderId: "1ekHiYUdFsm4LVH380xHBQU6KRurK-kGh", chatgptPrompt: `You are a social media content creator for Gake Sushi, a modern premium Japanese restaurant in Vancouver. Brand colors: warm beige, deep red (#8B1A1A), dark grey. Tone: modern Japanese, clean, premium casual. Focus on: premium sashimi, sake selection, bento boxes, holiday course menus. Write with modern sophistication.` },
  { active: true,  "Comme Living", nameKo: "꼼므 리빙", category: "Furniture / Home & Living", emoji: "🛋️", colors: ["#F0EDE8", "#D4C9BC", "#2C2C2C", "#A89880"], colorNames: ["Cream", "Warm Taupe", "Charcoal", "Mocha"], tone: ["Minimal", "Trendy", "Modern lifestyle", "Editorial"], instagram: "@commeliving", website: "https://commeliving.com", highlights: ["공동구매 프로모션", "Directly imported from Hyundai Livart Korea", "Living/interior styling", "Lifestyle branding"], schedule: "Weekly + Promotions", driveFolderId: "19no0wCFvVQPDBKUhr3yZN-EeW3KB3i0L", logoFolderId: "13aszmDNCK_xkoy8UVBxxHcgj_X0uBfgP", chatgptPrompt: `You are a social media content creator for Comme Living, a modern lifestyle furniture brand in Vancouver. Brand colors: cream, warm taupe, charcoal. Tone: minimal, trendy, modern lifestyle. Focus on: Korean-imported furniture (Hyundai Livart), interior styling, 공동구매 promotions, lifestyle branding. Write with clean, editorial style.` },
  { active: true,  "AcuPlus Clinic", nameKo: "ACU Plus", category: "Acupuncture & Facial Aesthetics", emoji: "🌿", colors: ["#FAFAF8", "#2D4A3E", "#E8E0D0", "#8BA888"], colorNames: ["Off White", "Dark Green", "Cream", "Sage"], tone: ["Professional", "Calming", "Premium wellness"], instagram: "@acuplus_ca", website: "https://acuplusclinic.com", highlights: ["Acupuncture", "Facial rejuvenation", "Osteopathy", "ICBC treatments", "Pain management", "Micro needling"], schedule: "Weekly", driveFolderId: "1fNl_tV037w7QVgMWR_pb7V24bguImGhB", logoFolderId: null, chatgptPrompt: `You are a social media content creator for AcuPlus Clinic, a premium acupuncture and facial aesthetics clinic in Vancouver. Brand colors: off white, dark green (#2D4A3E), cream, sage. Tone: professional, calming, premium wellness. Focus on: acupuncture benefits, facial rejuvenation, ICBC coverage, holistic wellness. Write with calm professionalism.` },
  { active: true,  "True Therapy Clinic", nameKo: "True Therapy", category: "RMT Clinic", emoji: "💆", colors: ["#FAFAF8", "#2D4A3E", "#E8E0D0", "#8BA888"], colorNames: ["Off White", "Dark Green", "Cream", "Sage"], tone: ["Professional", "Trustworthy", "Recovery-focused"], instagram: "@truetherapyclinic.ca", website: "https://truetherapyclinic.ca", highlights: ["Registered Massage Therapy", "ICBC direct billing", "Pain relief", "Recovery & rehabilitation", "Personalized treatments"], schedule: "Weekly", driveFolderId: "1Yv18zKi4Tf3z3Z0T4y2MxbU6djAPyRUv", logoFolderId: "16LBwbhwShGyRNTUrFRYi3H55ByflNtuC", chatgptPrompt: `You are a social media content creator for True Therapy Clinic, an RMT clinic in Vancouver. Brand colors: off white, dark green, cream, sage. Tone: professional, trustworthy, recovery-focused. Focus on: RMT services, ICBC direct billing, pain relief, personalized recovery care. Write with trustworthy professionalism.` },
  { active: true,  "Misty Blue Flowers", nameKo: "Misty Blue", category: "Florist / E-commerce", emoji: "💐", colors: ["#F5F3F0", "#8B9BB4", "#C4B8D4", "#D4C5B0"], colorNames: ["Soft White", "Muted Blue", "Lavender", "Warm Sand"], tone: ["Editorial", "Elegant", "Modern", "Expressive"], instagram: "@mistyblue.ca", website: "https://mistyblueflowers.ca", highlights: ["Flower arrangements", "Same-day delivery", "Seasonal collections", "Mother's Day / Graduation campaigns"], schedule: "Weekly + Holiday", driveFolderId: "1ncdb0-rlxgOIu7gn-5i4I2zkjO_7kK3v", logoFolderId: "1IILYa0cNwOPs0hkW5G8IzAMlRXQsVUFr", chatgptPrompt: `You are a social media content creator for Misty Blue Flowers, an editorial florist in Vancouver. Brand colors: soft white, muted blue (#8B9BB4), lavender, warm sand. Tone: editorial, elegant, modern, expressive. Focus on: unique flower arrangements, seasonal collections, same-day delivery, special occasion campaigns. Write with elegance and creativity.` },
  { active: true,  "Joayo Therapy", nameKo: "Joayo Therapy", category: "Wellness Clinic", emoji: "🧘", colors: ["#FFFFFF", "#1a1a1a", "#E8E4DF", "#9A9590"], colorNames: ["White", "Black", "Warm Grey", "Muted"], tone: ["Holistic", "Modern wellness", "Approachable", "Clean"], instagram: "@joayotherapy", website: "https://www.joayotherapy.ca/", highlights: ["Chiropractic", "Physiotherapy", "RMT", "Pilates", "Acupuncture", "Kinesiology", "Naturopathic Medicine"], schedule: "Weekly", driveFolderId: "1ktufJtDVYQwPPIKvMoDNEd1apjG9pXuY", logoFolderId: "1Y4idsJ9YHv7107MNZ17RRbW4g19VnqI3", chatgptPrompt: `You are a social media content creator for Joayo Therapy, a holistic wellness clinic in Vancouver. Brand colors: white, black, warm grey. Tone: holistic, modern wellness, approachable, clean. Focus on: comprehensive wellness services (chiro, physio, RMT, pilates, acupuncture), integrated care approach. Write with clean, modern wellness voice.` },
  { active: true,  "Joayo Pilates", nameKo: "Joayo Pilates", category: "Fitness / Pilates Studio", emoji: "🤸", colors: ["#FFFFFF", "#1a1a1a", "#F0EDE8", "#C8C0B8"], colorNames: ["White", "Black", "Cream", "Warm Grey"], tone: ["Modern", "Approachable", "Motivating", "Welcoming"], instagram: "@joayopilates", website: "TBD", highlights: ["Reformer Pilates", "Private Sessions", "Group Classes", "Core Strength", "Posture Improvement", "Beginner-Friendly"], schedule: "Weekly", driveFolderId: "1ktufJtDVYQwPPIKvMoDNEd1apjG9pXuY", logoFolderId: "1Y4idsJ9YHv7107MNZ17RRbW4g19VnqI3", chatgptPrompt: `You are a social media content creator for Joayo Pilates, a modern pilates studio in Vancouver. Brand colors: white, black, cream, warm grey. Tone: modern, approachable, motivating, welcoming. Focus on: reformer pilates, core strength, posture, injury prevention, sustainable fitness. Write with warm encouragement.` },
  { active: true,  "Chang's Taekwondo", nameKo: "태권도창스", category: "Martial Arts / Education", emoji: "🥋", colors: ["#1A2B6B", "#C0272D", "#1a1a1a", "#FFFFFF"], colorNames: ["Deep Blue", "Deep Red", "Black", "White"], tone: ["Motivational", "Disciplined", "Family-friendly", "Energetic"], instagram: "@changstaekwondo", website: "https://www.changstaekwondo.ca/", highlights: ["Taekwondo training", "Kids classes", "Cute illustrations for kids", "Discipline & confidence building"], schedule: "Weekly", driveFolderId: "1f_JyaB1U-IoU5zR-oeKrpTtcfH43Fn3g", logoFolderId: null, logoFolderId: null, chatgptPrompt: `You are a social media content creator for Chang's Taekwondo, a martial arts school in Vancouver. Brand colors: deep blue, deep red, black, white. Tone: motivational, disciplined, family-friendly. Focus on: taekwondo for kids and adults, confidence building, discipline, fun learning environment. Write with energy and family warmth.` },
  { active: true,  "Queen's Therapy", nameKo: "Queen's Therapy", category: "Acupuncture & RMT Clinic", emoji: "👑", colors: ["#F2EBE0", "#8B9E7A", "#6B7A5E", "#5C4A3A", "#3A3A3A"], colorNames: ["Warm Beige", "Sage Green", "Olive", "Mocha", "Charcoal"], tone: ["Warm", "Calming", "Professional", "Premium wellness"], instagram: "@queenstherapycoquitlam", website: "https://queenstherapy.janeapp.com", highlights: ["Acupuncture", "Glass/Fire Cupping", "RMT", "Facial Rejuvenation", "HIFU Ultrasound", "ICBC treatments", "Body Slim Therapy"], schedule: "Weekly", driveFolderId: "1PjmjBgyI0g1lx5EZYebR015eRS6W-uy4", logoFolderId: null, chatgptPrompt: `You are a social media content creator for Queen's Therapy, a premium acupuncture and RMT clinic in Coquitlam, Vancouver. Brand colors: warm beige, sage green, olive, mocha, charcoal. Tone: warm, calming, professional, premium wellness. Focus on: acupuncture, cupping, RMT, facial rejuvenation, ICBC coverage, holistic skin wellness, HIFU treatment. Write with warm professionalism.` },
  { active: true, id: "wolha", name: "WOLHA", nameKo: "월하", category: "Premium Korean Rice Wine", emoji: "🌕", colors: ["#17244A", "#C6A27B", "#F3EEE5", "#8B6B53", "#1D1A1A"], colorNames: ["Midnight Navy", "Warm Gold", "Ivory", "Clay Brown", "Charcoal Black"], tone: ["Calm", "Artisan", "Minimal", "Sophisticated", "Quiet Luxury"], instagram: "@wolha_ricewine", website: "https://wolha.ca", highlights: ["Premium Korean Rice Wine", "Small batch fermentation", "Vancouver Exclusive", "Natural fermentation", "Alive with probiotics", "Handcrafted", "Modern Korean craft"], schedule: "Weekly", driveFolderId: "1DJ79pEQpeIl-spEaZzqeCbF1c9mDta4t", logoFolderId: null, chatgptPrompt: `You are a social media content creator for WOLHA (월하), a premium Korean rice wine brand in Vancouver. Brand colors: midnight navy (#17244A), warm gold (#C6A27B), ivory (#F3EEE5). Tone: calm, artisan, minimal, sophisticated, quiet luxury. This is NOT a party drink — it is a premium fermented craft beverage. Focus on: slow fermentation, handcrafted small batches, natural probiotics, modern Korean craft culture, pairing with fine food. Target: 30-50 Vancouver food lovers, natural wine drinkers, sake enthusiasts, wellness-conscious consumers. NEVER use: cheap, party, fun, cute, trendy, K-pop vibes. Always write with quiet elegance and depth.` },
];

export const categories = ["All", "Restaurant", "Sushi", "Wellness", "Fitness", "Retail", "Florist", "Martial Arts", "Beverage"];

export const categoryMap = {
  Restaurant: ["cocoricocafe", "onggi", "twohorns"],
  Sushi: ["gamisushi", "gakesushi"],
  Wellness: ["acuplus", "truetherapy", "joayotherapy", "queenstherapy"],
  Fitness: ["joayopilates", "changstaekwondo"],
  Retail: ["commeliving"],
  Florist: ["mistyblue"],
  "Martial Arts": ["changstaekwondo"],
  Beverage: ["wolha"],
};
